apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: k8s-pruchay-com-tls
spec:
  secretName: k8s-pruchay-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.pruchay.com
  dnsNames:
    - k8s.pruchay.com
